### ISSUE TITLE
Certifcate Expires 

### ISSUE THREAD

**Issue by N1v0k** [janeczku/rancher-letsencrypt#102]
I'm getting e-mails because my certificates will expire.
They state that e.g.:

> Your certificates (...) will expire in 9 Days (on 14. Nov 17 07:11 +0000) ....

But the container logs show this:

```
11/4/2017 9:01:14 AMINFO[0000] Starting Let's Encrypt Certificate Manager v0.5.0 0913231
11/4/2017 9:01:14 AMINFO[0000] Using locally stored Let's Encrypt account for ****@*****.com
11/4/2017 9:01:14 AMINFO[0000] Using Let's Encrypt Production API
11/4/2017 9:01:14 AMINFO[0000] Found locally stored certificate 'r-ssl-main'
11/4/2017 9:01:14 AMINFO[0000] Found existing certificate 'r-ssl-main' in Rancher
11/4/2017 9:01:14 AMINFO[0000] Managing renewal of certificate 'r-ssl-main'
11/4/2017 9:01:14 AMINFO[0000] Certificate renewal scheduled for 2018/01/09 12:00 UTC
```

How can I fix this issue?

I'm using AWS R53 btw.

The configuration is:

```
  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.5.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY: *******
      AWS_SECRET_KEY: *******
      CERT_NAME: r-ssl-main
      DOMAINS: ****.com, *****.com, *****.com, *****.com, *****.com, ***.sh, ****.sh
      EMAIL: *****@***.com
      EULA: 'Yes'
      PROVIDER: Route53
      RENEWAL_TIME: '12'
      PUBLIC_KEY_TYPE: RSA-2048
    stdin_open: true
    volumes:
    - /var/lib/rancher:/var/lib/rancher
    - /srv/docker/net/letsencrypt:/etc/letsencrypt
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
```
