### ISSUE TITLE
can't make it work with rancher-nfs

### ISSUE THREAD

**Issue by ihackalot** [janeczku/rancher-letsencrypt#47]
Have no problems at storing certificates on data volume containers inside host, but I'm not able to make it work with rancher-nfs and digitalocean block volume.

I attach the volume to rancher server host and spin up the rancher driver on agent host giving the ip of my rancher server and `/mnt/volume-name` as mount point.

The volume becomes available, but I'm not able to tell letsencrypt to use it.

**Comment by gizmotronic** [comment]
Speaking from an end user perspective, my experience is the opposite. In fact, I have three letsencrypt containers (for different certificates) that share the same rancher-nfs volume.

**Comment by ihackalot** [comment]
Could you please shed more light on this? How do you setup nfs server and how you tell the catalog template it's a rancher-nfs driver?

**Comment by gizmotronic** [comment]
I think the key thing that I did was to manually create a container using the Rancher interface, first. If you deploy your container using the `Add Container` button under `Infrastructure` > `Containers`, you can specify the driver under the `Volumes` tab. The storage volume will be created automatically for you, in this case. I'm not sure whether there's a way to do it directly under `Infrastructure` > `Storage`.

Here's an example of the docker-compose.yml I've currently deployed. (Environment is omitted, but of course necessary.)

```
version: '2'
volumes:
  cert-manager:
    external: true
    driver: rancher-nfs
services:
  letsencrypt-N:
    image: janeczku/rancher-letsencrypt:v0.3.0
    volumes:
    - cert-manager:/etc/letsencrypt
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'
```

I configured Rancher NFS to connect to an Ubuntu 16.04.1 server. Any storage volumes you create/use are relative to the mount path you specify when configuring Rancher NFS; so if you mount my-nfs-host.example.com:/shared, the cert-manager volume listed above is /shared/cert-manager on your NFS server.

My only complaint with this setup is that I can only mount one NFS server as shared storage. I actually have 2, one of which is primary persistent storage, and the other a read-only media store. But that's another topic, entirely...
